### ISSUE TITLE
Filter data pass array down, and onRowClick data disappear

### ISSUE THREAD

**Issue by madebymt** [gregnb/mui-datatables#1331]
When I first fetch the data, filter out the categories, then pass the array to mui-datatables to display, but onRowClick action will trigger another request to get more detail, weird things my row will disappear when row click after couple second.
Take me couple hours to figure why cause it, I have redux-selector getting the state, filter out by the user button click (ex: If they click a cookie, filter out the API result just cookie categories)
I comment out of the filter function then the row won't disappear, but I need filter from different types because I don't want to use manually to do so.

Does anyone know how I can fix it or have some issue as I have? 
Can I get grab the mui-datatables filter function out and create a button in the UI? Trigger that table filter function by clicking a button, not from the table?

I was trying to set up a code sandbox, it's a massive codebase, sorry about that.

Thank you so much again for this package, make my loading a lot of data so much easier, and they look great!

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.11      |
| MUI-datatables  |   2.14.0      |
| React        |    16.8 I beleive     |
| browser      |   Chrome      |
| etc          |         |

**Comment by patorjk** [comment]
@madebymt This sounds like the state/props issue that was fixed in version 2.15.0 of the table. Prior to version 2.15.0, the table would reset internal state on re-render (ie, options that weren't passed in as props would be reset). As of version 2.15.0, internal state is maintained on re-render.

Also, version 3.0.0 is out (3.0.1 will most likely release on Monday). As long as you're using Material UI 4.x, you everything should work the same (it's mostly a major version bump because from 3.x on, support will focus on material-ui v4).

**Comment by madebymt** [comment]
@patorjk  Thank you so much for the quick response. I will try that later and hoping will fix that and I'll let you know. Please let me know if you guys have the Patreon page or PayPal link, so we can support this library. Thanks!

**Comment by patorjk** [comment]
No prob, hope it helped you! No patreon or paypal link, though I'll post a note here if one is ever added.

**Comment by madebymt** [comment]
Hi @patorjk I'm still see the row disappeared when row click when I pass a filter data down. Do we have any way can work around this? Can I access the filter function build in the table ? Thanks

**Comment by patorjk** [comment]
Is it possible to create a small example using a codesandbox? You don't need your full setup, just something demonstrating the problem.

You can override how filters work using filterOptions, and the list of filters for a particular column are held in a column's options.filterList array.

**Comment by madebymt** [comment]
Hi, I tried to re-create in the code sandbox box it's not happened in there, maybe because my app use remote data? this sample I use is hardcode data.
It's only happened when I filter the data and pass down to the table, and onRowClick a couple second later will be gone.
Thank you for help me investigate this.
https://codesandbox.io/s/beautiful-jennings-9g92g?file=/src/App.js

**Comment by patorjk** [comment]
Remote data shouldn't have any affect. One thing to check would be your data before the table is rendered. Example:

```
import cloneDeep from 'lodash.clonedeep';

console.dir( cloneDeep (data) );
return ( <MUIDataTable data={...} /> );
```

This would tell you if the disappearance was happening because the row is being removed from the data. Also, what is occuring inside your onRowClick? Does the issue happen even if there's just a console statement?

**Comment by madebymt** [comment]
Thank you for your suggestion, I add it in my codesandbox, here my console.log
```
["Joe James", "Test Corp", "Yonkers", Object]
```

and I did get a console warning on click
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of t which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in th (created by ForwardRef(TableCell))
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    in WithStyles(ForwardRef(TableCell)) (created by t)
    in t (created by WithStyles(t))
    in WithStyles(t) (created by r)
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
```

Thank you!

**Comment by patorjk** [comment]
The table has two issues with strict mode:

* There are several findDOMNode calls (these are done for the header cells for resizable columns). In the next release (3.1.0), these will all be refactored out.
* The main component has a UNSAFE_componentWillMount lifecycle method. This is on my list to refactor out. Will probably be in the 3.2.0 or 3.1.1 release.

I think that even though they're deprecated, things will still work fine.

**Comment by madebymt** [comment]
HI @patorjk 
Thank you for your response. I just update to version 3.1.3. I find all my custom action row click will cause the row data missing. I log my state of the array is correct, but the table just deletes it for somehow, total number in the footer will change. and can't find the row of data use searching tools.

Please let me know if I have any way to work around this for pass a filter data arrays to the mui-datatables component, I've been stuck with this about a month. Thank you so much!

**Comment by patorjk** [comment]
Are you passing in searchText or a filterList? If so, are you sure the row in question isn't being filtered out?

Add this:

console.dir(columns);
console.dir(options);

And paste in what is displayed after the row click that causes the row not to be displayed. I'm wondering if you're passing something into the table on re-render that is causing the data not to display.

**Comment by madebymt** [comment]
Thank you for your suggestion, I found out my remote data is causing the issue when I filter. Sorry about that. We can close this issue now.

**Comment by patorjk** [comment]
No worries, thank you for the update!
